// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, metrics;

  express = require('express');

  app = express();

  metrics = require('./metrics');

  require('jstransformer-coffee-script');

  app.use(require('body-parser')());

  app.set('port', 1889);

  app.set('views', __dirname + "/../views");

  app.set('view engine', 'jade');

  app.use('/', express["static"](__dirname + "/../public"));

  app.get('/', function(req, res) {
    return res.render('index', {
      locals: {
        title: 'ECE AST'
      }
    });
  });

  app.get('/metrics.json', function(req, res) {});

  res.status(200).JSON(metrics.get());

  app.get('/hello/:name', function(req, res) {
    return res.status(200).send(req.params.name);
  });

  app.post('/metrics/:id.json', function(req, res) {});

  metric.save(req.params.id, req.body, function(err) {});

  if (err) {
    res.status(500).json(err);
  }

  res.status(200).send("Metrics Saved");

  app.listen(app.get('port'), function() {});

  console.log("server listening on " + (app.get('port')));

}).call(this);
