// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')("#[__dirname}/../db/metrics");

  module.exports = {

    /* 
    `get()`
    -------
    returns some hard-coded metrics
     */
    get: function(username, callback) {
      var metric, metrics, readstream;
      metrics = {};
      metric = {};
      readstream = db.createReadStream({
        gte: "metrics:" + username,
        lte: "metrics:" + username
      });
      readstream.on('data', function(data) {
        var value;
        value = data.value.split(':');
        metric.push({
          timestamp: value[1]
        }, value[2]);
        return metric;
      });
      readstream.on('error', callback);
      return readstream.on('close', function() {
        return callback(null, metric);
      });
    },

    /*
    save(id, metrics ,cb)
    ---------------------------------
    save some metrics with a given id
    
    Parameters:
    'id': an integer defining a batch of metrics
    'metric': An array of objects with a timestamp and a value
    'callback': Callback function called at the end or on error
     */
    save: function(id, metrics, callback) {
      var count, i, len, metric, timestamp, value, ws;
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      for (count = i = 0, len = metrics.length; i < len; count = ++i) {
        metric = metrics[count];
        timestamp = metric.timestamp, value = metric.value;
        ws.write({
          key: "metric:" + id + ":" + (count + 1),
          value: "metrics:" + timestamp + ":" + value
        });
      }
      console.log("Metrics saved.");
      return ws.end();
    }
  };

}).call(this);
