// Generated by CoffeeScript 1.10.0
(function() {
  var http, user;

  http = require('http');

  user = require('./user.js');

  http.createServer(function(req, res) {
    var path;
    path = req.url.split('/');
    if (path[1] === 'get') {
      user.get(path[2], function(user) {
        var response;
        response = {
          info: 'Information the User',
          user: user
        };
        res.writeHead(200, {
          content: 'application/json'
        });
        res.end(JSON.stringify(response));
      });
    } else if (path[1] === 'save') {
      user.save(path[2], function(user) {
        var response;
        response = {
          info: 'The user was saved',
          user: user
        };
        res.writeHead(200, {
          content: 'application/json'
        });
        res.end(JSON.stringify(response));
      });
    } else {
      res.writeHead(404, {
        content: 'text/plain'
      });
      res.end('404 Error : Not Found');
    }
  }).listen(1337, '127.0.0.1');

}).call(this);
