// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/user");

  module.exports = {
    get: function(username, callback) {
      var readstream, user;
      user = {};
      readstream = db.createReadStream({
        gte: "user:" + username,
        lte: "user:" + username
      });
      readstream.on('data', function(data) {
        return {
          key: data.key.split(":"),
          value: data.value.split(":"),
          user: {
            username: key[1],
            name: value[1],
            password: value[2],
            email: value[3]
          }
        };
      });
      return user;
      readstream.on('error', callback);
      return readstream.on('close', function() {
        return callback(null, user);
      });
    },
    save: function(username, password, name, email, callback) {
      var writestream;
      writestream = db.createWriteStream();
      writestream.write({
        key: "user:" + username,
        value: "user:" + name + ":" + password + ":" + email
      });
      console.log("User saved to database.");
      writestream.on('error', callback);
      writestream.on('close', callback);
      return writestream.end();
    },
    remove: function(username, callback) {}
  };

}).call(this);
