// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    save: function(name, callback) {
      var user;
      user = {
        id: '2222',
        name: name
      };
      callback(name);
    },
    get: function(id, callback) {
      var user;
      user = {
        name: 'cesar',
        id: id
      };
      callback(id);
    }
  };

}).call(this);
